version: "3.8"

services:
  web:
    build:
      context: .
      args:
        - DJANGO_PORT=${DJANGO_PORT}
    env_file:
      - .env
    volumes:
      - .:/code
    networks:
      - django-network
    ports:
      - ${SERVER_PORT}:${DJANGO_PORT}
    depends_on:
      - db
      - redis
  db:
    image: mariadb:10.8
    ports:
      - "30000:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - database:/var/lib/mysql
    networks:
      - django-network
  redis:
    image: "redis:7.0-alpine"
    networks:
      - django-network
  celery:
    build:
      context: .
      args:
        - IN_PORT=$IN_PORT
    command: celery -A http_monitoring_system worker -l info
    volumes:
      - .:/code
    networks:
      - django-network
    depends_on:
      - db
      - redis
    env_file:
      - .env
  celery-beat:
    build: .
    command: celery -A http_monitoring_system beat -l info
    volumes:
      - .:/code
    networks:
      - django-network
    depends_on:
      - db
      - redis
    env_file:
      - .env
networks:
  django-network:
    name: django-network
volumes:
  database:
