# Generated by Django 4.2.6 on 2024-01-31 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website',
            new_name='Server',
        ),
    ]
