# run_kube:
#     kubectl apply -f secret.yml
#     kubectl apply -f mariadb-statefulset.yml
#     kubectl apply -f mariadb-read-service.yml
#     kubectl apply -f mariadb-write-service.yml
#     kubectl apply -f config-map.yml
#     kubectl apply -f deployment.yml
#     kubectl apply -f service.yml
