apiVersion: v1
kind: Service
metadata:
  name: http-monitoring-service
spec:
  selector:
    app: http-monitoring-deployment
  ports:
    - protocol: TCP
      port: 2020
      targetPort: 8000
  type: LoadBalancer
